In [1]:

import pandas as pd
import numpy as np
from sklearn import pipeline,preprocessing,metrics,model_selection,ensemble
from sklearn_pandas import DataFrameMapper

In [2]:
data=pd.read_csv('diabetes.csv')
data.head()
#data.isnull().sum()
#pd.read_csv? 'it helps to know about parameters of this function
#data.shape 'it  return total number of rows & col in the form (row , col)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
data.info() #not null means no row contain missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [4]:
data.describe() #'give statistical measure like count , mean , min etc

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [5]:
data['Outcome'].value_counts() #count values of 0 and 1 in outcome , 1 is diabetes +

0    500
1    268
Name: Outcome, dtype: int64

In [6]:
data.groupby('Outcome').mean() # calcuate mean for all row in value 0 & 1

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

In [7]:
mapper = DataFrameMapper([
                        (['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age'], preprocessing.StandardScaler())
                        ])
pipeline_obj = pipeline.Pipeline([
    ('mapper',mapper),
    ("model", ensemble.RandomForestRegressor())
])

In [8]:
X=['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age']
Y=['Outcome']
pipeline_obj.fit(data[X],data[Y])
pipeline_obj.predict(data[X])

c:\users\dell\miniconda3\lib\site-packages\sklearn\pipeline.py:346: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params_last_step)

array([0.89, 0.03, 0.95, 0.  , 0.87, 0.  , 0.6 , 0.29, 0.93, 0.74, 0.05,
       0.96, 0.1 , 0.72, 0.86, 0.69, 0.91, 0.76, 0.19, 0.85, 0.12, 0.13,
       0.97, 0.8 , 0.84, 0.74, 0.9 , 0.  , 0.13, 0.15, 0.25, 0.94, 0.  ,
       0.  , 0.33, 0.09, 0.3 , 0.86, 0.66, 0.73, 0.36, 0.32, 0.06, 0.93,
       0.21, 0.92, 0.15, 0.  , 0.77, 0.22, 0.  , 0.01, 0.  , 0.92, 0.33,
       0.01, 0.94, 0.16, 0.28, 0.03, 0.  , 0.8 , 0.  , 0.09, 0.87, 0.09,
       0.81, 0.19, 0.  , 0.15, 0.68, 0.16, 0.82, 0.06, 0.03, 0.  , 0.  ,
       0.08, 0.93, 0.  , 0.  , 0.  , 0.17, 0.01, 0.87, 0.17, 0.09, 0.02,
       0.81, 0.  , 0.  , 0.22, 0.05, 0.6 , 0.07, 0.18, 0.07, 0.  , 0.07,
       0.86, 0.95, 0.11, 0.05, 0.  , 0.11, 0.07, 0.02, 0.11, 0.02, 0.58,
       0.9 , 0.81, 0.08, 0.01, 0.94, 0.89, 0.76, 0.12, 0.  , 0.  , 0.91,
       0.14, 0.06, 0.07, 0.67, 0.82, 0.21, 0.1 , 0.79, 0.73, 0.91, 0.96,
       0.97, 0.07, 0.01, 0.19, 0.02, 0.01, 0.24, 0.08, 0.08, 0.16, 0.08,
       0.77, 0.08, 0.  , 0.01, 0.24, 0.23, 0.  , 0.15, 0.01, 0.93, 0.06,
       0.92, 0.85, 0.  , 0.01, 0.  , 0.89, 0.15, 0.11, 0.08, 0.01, 0.8 ,
       0.82, 0.13, 0.34, 0.1 , 0.06, 0.72, 0.75, 0.05, 0.08, 0.03, 1.  ,
       0.03, 0.88, 0.29, 0.85, 0.01, 0.11, 0.03, 0.  , 0.1 , 0.99, 0.84,
       0.94, 0.92, 0.67, 0.  , 0.21, 0.88, 0.89, 0.  , 0.88, 0.  , 0.58,
       0.74, 0.75, 0.17, 0.12, 0.3 , 0.  , 0.15, 0.01, 0.95, 0.88, 0.02,
       1.  , 0.  , 0.33, 0.35, 0.79, 0.84, 0.87, 0.74, 0.18, 0.61, 0.82,
       0.95, 0.85, 0.06, 0.13, 0.03, 0.04, 0.03, 0.92, 0.27, 0.13, 0.77,
       0.88, 0.  , 0.13, 0.01, 0.96, 0.97, 0.99, 0.94, 0.  , 0.  , 0.01,
       0.62, 0.76, 0.21, 0.93, 0.35, 0.14, 0.22, 0.03, 0.18, 0.08, 0.  ,
       0.  , 0.8 , 0.73, 0.25, 0.  , 0.28, 0.87, 0.43, 0.91, 0.03, 0.15,
       0.87, 0.17, 0.97, 0.33, 0.  , 0.77, 0.75, 0.  , 0.04, 0.05, 0.15,
       0.08, 0.69, 0.  , 0.04, 0.09, 0.73, 0.24, 0.18, 0.91, 0.7 , 0.07,
       0.23, 0.78, 0.  , 0.13, 0.1 , 0.51, 0.9 , 0.76, 0.08, 0.31, 0.73,
       0.02, 0.68, 0.05, 0.96, 0.84, 0.1 , 0.88, 0.08, 0.05, 0.82, 0.04,
       0.75, 0.79, 0.01, 0.04, 0.78, 0.07, 0.94, 0.01, 0.01, 0.95, 0.03,
       0.81, 0.14, 0.62, 0.86, 0.73, 0.05, 0.2 , 0.74, 0.34, 0.7 , 0.18,
       0.08, 0.04, 0.86, 0.08, 0.  , 0.4 , 0.35, 0.83, 0.92, 0.97, 0.02,
       0.02, 0.04, 0.05, 0.12, 0.14, 0.16, 0.03, 0.  , 0.64, 0.04, 0.13,
       0.05, 0.  , 0.07, 0.86, 0.79, 0.86, 0.11, 0.99, 1.  , 0.18, 0.17,
       0.89, 0.22, 0.05, 0.71, 0.01, 0.02, 0.76, 0.88, 0.05, 0.03, 0.01,
       0.2 , 0.86, 0.  , 0.13, 0.93, 0.1 , 0.05, 0.  , 0.06, 0.01, 0.01,
       0.  , 0.83, 0.71, 0.88, 0.13, 0.17, 0.9 , 0.08, 0.01, 0.96, 0.12,
       0.01, 0.79, 0.  , 0.88, 0.57, 0.14, 0.75, 0.  , 0.91, 0.12, 0.88,
       0.01, 0.89, 0.87, 0.21, 0.13, 0.21, 0.05, 0.82, 0.91, 0.02, 0.85,
       0.  , 0.6 , 0.11, 0.01, 0.08, 0.01, 0.9 , 0.96, 0.01, 0.97, 0.24,
       0.73, 0.  , 0.01, 0.03, 0.08, 0.03, 0.92, 0.24, 0.15, 0.  , 0.12,
       0.9 , 0.01, 0.01, 0.93, 0.75, 0.81, 0.01, 0.04, 0.67, 0.09, 0.  ,
       0.61, 0.05, 0.07, 0.01, 0.75, 0.2 , 0.  , 0.94, 0.15, 0.05, 0.  ,
       0.1 , 0.05, 0.1 , 0.02, 0.  , 0.05, 0.74, 0.22, 0.19, 0.21, 0.08,
       0.17, 0.03, 0.14, 0.78, 0.1 , 0.05, 0.16, 0.89, 0.14, 0.02, 0.04,
       0.95, 0.86, 0.25, 0.38, 0.01, 0.25, 0.02, 0.06, 0.07, 0.91, 0.  ,
       0.18, 0.01, 0.01, 0.92, 0.21, 0.01, 0.01, 0.75, 0.14, 0.13, 0.03,
       0.93, 0.04, 0.01, 0.03, 0.64, 0.03, 0.05, 0.01, 0.  , 0.79, 0.94,
       0.13, 0.13, 0.11, 0.01, 0.07, 0.05, 0.95, 0.15, 0.  , 0.  , 0.  ,
       0.04, 0.02, 0.05, 0.12, 0.07, 0.15, 0.21, 0.88, 0.12, 0.03, 0.11,
       0.86, 0.8 , 0.78, 0.67, 0.1 , 0.01, 0.98, 0.96, 0.15, 0.28, 0.34,
       0.01, 0.03, 0.09, 0.  , 0.02, 0.09, 0.08, 0.18, 0.12, 0.09, 0.77,
       1.  , 0.  , 0.07, 0.07, 0.01, 0.01, 0.08, 0.19, 0.75, 0.01, 0.05,
       0.  , 0.  , 0.19, 0.14, 0.04, 0.69, 0.13, 0.92, 0.72, 0.02, 0.1 ,
       0.07, 0.77, 0.  , 0.82, 0.07, 0.95, 0.02, 0.95, 0.03, 0.85, 0.08,
       0.22, 0.93, 0.08, 0.01, 0.93, 0.01, 0.01, 0.01, 0.15, 0.93, 0.86,
       0.18, 0.97, 0.  , 0.16, 0.  , 0.  , 0.95, 0.99, 0.16, 0.93, 0.01,
       0.13, 0.  , 0.86, 0.72, 0.09, 0.08, 0.3 , 0.01, 0.01, 0.04, 0.02,
       0.17, 0.3 , 0.01, 0.84, 0.01, 0.  , 0.05, 0.03, 0.75, 0.1 , 0.03,
       0.72, 0.01, 0.09, 0.18, 0.73, 0.07, 0.12, 0.32, 0.91, 0.93, 0.83,
       0.  , 0.  , 0.02, 0.09, 0.06, 0.04, 0.82, 0.02, 0.32, 0.13, 0.73,
       0.24, 0.96, 0.92, 0.9 , 0.79, 0.04, 0.77, 0.73, 0.12, 0.3 , 0.37,
       0.01, 0.1 , 0.29, 0.1 , 0.88, 0.73, 0.01, 0.6 , 0.  , 0.  , 0.88,
       0.03, 0.76, 0.17, 0.15, 0.05, 0.09, 0.03, 0.89, 0.02, 0.88, 0.08,
       0.87, 0.  , 0.83, 0.92, 0.  , 0.15, 0.13, 0.01, 0.81, 0.95, 0.27,
       0.04, 0.04, 0.7 , 0.15, 0.91, 0.68, 0.16, 0.16, 0.85, 0.09, 0.15,
       0.97, 0.99, 0.08, 0.04, 0.72, 0.02, 0.02, 0.72, 0.18, 0.23, 0.18,
       0.03, 0.17, 0.23, 0.  , 0.73, 0.74, 0.99, 0.  , 0.09, 0.02, 0.01,
       0.03, 0.02, 0.68, 0.9 , 0.06, 0.04, 0.93, 0.28, 0.17, 0.83, 0.11,
       0.96, 0.83, 0.88, 0.01, 0.01, 0.94, 0.8 , 0.91, 0.17, 0.87, 0.06,
       0.79, 0.02, 1.  , 0.  , 0.12, 0.02, 0.  , 0.89, 0.  ])

In [9]:
import joblib
joblib.dump(pipeline_obj,'diabetesRFC.pkl')

['diabetesRFC.pkl']

In [10]:
temp={}
temp['Pregnancies']=1
temp['Glucose']=85
temp['BloodPressure']=66
temp['SkinThickness']=29
temp['Insulin']=0
temp['BMI']=26.6
temp['DiabetesPedigreeFunction']=0.351
temp['Age']=31

In [11]:
testDtaa=pd.DataFrame({'x':temp}).transpose()
testDtaa

,Age,BMI,BloodPressure,DiabetesPedigreeFunction,Glucose,Insulin,Pregnancies,SkinThickness
x,31.0,26.6,66.0,0.351,85.0,0.0,1.0,29.0

In [13]:
loaddiabetesRFC=joblib.load('diabetesRFC.pkl')
print(loaddiabetesRFC.predict(testDtaa)[0]*100,'% possibility of having diabetes')

3.0 % possibility of having diabetes